// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABUKo94GLZCk4GO_LsvHhGGwChDOH5_sw',
    appId: '1:141406975230:web:5bbd984d2a739e21d3a1af',
    messagingSenderId: '141406975230',
    projectId: 'final-4cf8b',
    authDomain: 'final-4cf8b.firebaseapp.com',
    databaseURL: 'https://final-4cf8b-default-rtdb.firebaseio.com',
    storageBucket: 'final-4cf8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBjv6gX45Vp_du_pPgxmtcj5ZG1IeEQH0',
    appId: '1:141406975230:android:fcbdb4585a09dc2ad3a1af',
    messagingSenderId: '141406975230',
    projectId: 'final-4cf8b',
    databaseURL: 'https://final-4cf8b-default-rtdb.firebaseio.com',
    storageBucket: 'final-4cf8b.appspot.com',
  );

}